name: Test Go project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GOTOOLCHAIN: "local" 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Install dependencies
        run: |
          go mod tidy
          go version
          go env

      - name: Run tests
        run: go test -v ./...
