name: Test Go project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Print DB schema (optional)
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3
          sqlite3 tracker.db '.schema'

      - name: Run tests
        run: go test -v ./...
